matrix:
  include:
    # Job 1) Run analyzer
    - os: linux
      env:
        - SHARD=Analyze
      sudo: false
      addons:
        apt:
          # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
          sources:
            - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
          packages:
            - libstdc++6
            - fonts-droid
      before_script:
        - git clone https://github.com/flutter/flutter.git
        - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
        - flutter doctor
        - pub global activate flutter_plugin_tools
      script:
        - ./script/incremental_build.sh analyze
    # Job 2) Check format and run tests
    - os: linux
      env:
        - SHARD=Format+Test
      jdk: oraclejdk8
      sudo: false
      addons:
        apt:
          # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
          sources:
            - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
            - llvm-toolchain-precise # for clang-format-5.0
          packages:
            - libstdc++6
            - fonts-droid
            - clang-format-5.0
      before_script:
        - git clone https://github.com/flutter/flutter.git
        - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
        - flutter doctor
        - pub global activate flutter_plugin_tools
      script:
        - ./script/incremental_build.sh format --travis --clang-format=clang-format-5.0
        - ./script/incremental_build.sh test
    # Job 3) Build example APKs and run Java tests, shard 1/1
    - os: linux
      env:
        - SHARD="Build example apks 1/1"
        - PLUGIN_SHARDING="--shardIndex 0 --shardCount 1"
      jdk: oraclejdk8
      sudo: false
      addons:
        apt:
          # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
          sources:
            - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
          packages:
            - lib32stdc++6 # https://github.com/flutter/flutter/issues/6207
            - libstdc++6
            - fonts-droid
      before_script:
        - ./script/before_build_apks.sh
        - export ANDROID_HOME=`pwd`/android-sdk
        - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
      script:
        - ./script/incremental_build.sh build-examples --apk
        - ./script/incremental_build.sh java-test  # must come after apk build
    # Job 4) Build example IPAs, shard 1/1
    - os: osx
      env:
        - SHARD="Build example ipas 1/1"
        - PLUGIN_SHARDING="--shardIndex 0 --shardCount 1"
      language: generic
      osx_image: xcode10.2
      before_script:
        - ./script/before_build_ipas.sh
        - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
      script:
        - ./script/incremental_build.sh build-examples --ipa

cache:
  directories:
    - $HOME/.pub-cache
